//! P4-14 (#467): the classic decode sequence honours
//! `cinfo->mem->max_memory_to_use`.
//!
//! The memory-manager vtable has enforced the field since #519, but the
//! documented consumer sequence — `jpeg_read_header` →
//! `jpeg_start_decompress` → `jpeg_read_scanlines` — ran the native decoder
//! with default limits and was unbounded. That sequence is exactly what
//! issue #467 names.
//!
//! What upstream actually bounds is measured, not assumed
//! (`examples/classic_budget_oracle.c` vs stock 3.1.4.1): the field is
//! consulted only by `realize_virt_arrays` during `jpeg_start_decompress`,
//! and whole-image coefficient arrays exist only for multi-scan streams
//! (progressive *or* non-interleaved sequential — `has_multiple_scans`,
//! `jdinput.c:153-156`) and for buffered-image mode (`jdmaster.c:709`). A
//! 1000-byte budget therefore passes a *baseline* 64×64 decode untouched
//! and fails the multi-scan/buffered ones at `jpeg_start_decompress` with
//! `JERR_NO_BACKING_STORE` (51) — except the class whose arrays all fit
//! one access window, which upstream's `max_minheights >= 1` clamp
//! realizes at any positive budget (`short_progressive_tiny` below).
//!
//! What upstream *counts* is only those coefficient arrays — not output
//! buffers or component planes. The `big_progressive_midband` case pins
//! that: 1024×1024 grayscale progressive needs exactly 2 MiB of
//! coefficient blocks, and a 4 MiB budget must ACCEPT even though a
//! whole-pipeline estimate would exceed it (review of e492da9 measured a
//! 4.7× over-refusal band against stock when the port compared its
//! pipeline estimate instead).

use std::cell::Cell;
use std::ffi::{c_int, c_long, c_void};

mod helpers;

use libjpeg_turbo_rs_capi::jpeglib::{
    jpeg_destroy_compress, jpeg_destroy_decompress, jpeg_finish_compress, jpeg_finish_decompress,
    jpeg_finish_output, jpeg_has_multiple_scans, jpeg_input_complete, jpeg_mem_dest, jpeg_mem_src,
    jpeg_read_header, jpeg_read_scanlines, jpeg_set_defaults, jpeg_simple_progression,
    jpeg_start_compress, jpeg_start_decompress, jpeg_start_output, jpeg_std_error,
    jpeg_write_scanlines, JpegCompressPublic, JpegDecompressPublic, JpegErrorMgr,
};
use libjpeg_turbo_rs_capi::memmgr::JpegMemoryMgr;

/// `jpeglib.h`: `JCS_GRAYSCALE`.
const JCS_GRAYSCALE: c_int = 1;
/// `jerror.h`: `JERR_NO_BACKING_STORE`. 51 in the v8 table we ship (the
/// pre-v7 table has it at 49 — the `JPEG_LIB_VERSION` guards ahead of it
/// net two extra entries at v7+).
const JERR_NO_BACKING_STORE: c_int = 51;

/// A 64×64 RGB multi-scan *sequential* JPEG (SOF0, three single-component
/// scans `Ss=0 Se=63 Ah=Al=0`) generated by stock `cjpeg -quality 90
/// -scans`. `jpeg_has_multiple_scans()` is TRUE for it while
/// `progressive_mode` stays FALSE — the source shape that separates
/// upstream's gate from a progressive-only one. The shim's classic
/// compress does not honour custom `scan_info` scripts, so this one is a
/// committed fixture rather than built in-process like the others.
const MSS_FIXTURE: &[u8] = include_bytes!("fixtures/mss_64x64.jpg");

/// Source shapes, mirroring the oracle's `enum src_kind`.
#[derive(Clone, Copy, PartialEq)]
enum SrcKind {
    /// Single-scan grayscale 64×64.
    Baseline,
    /// Progressive grayscale 64×64.
    Progressive,
    /// Multi-scan sequential RGB 64×64 (the fixture above).
    Mss,
    /// Progressive grayscale 1024×1024 — 2 MiB of coefficient blocks.
    BigProgressive,
    /// Progressive grayscale 64×8 — one row of blocks, so every
    /// coefficient array fits a single access window and upstream
    /// realizes it at ANY positive budget (`max_minheights >= 1` clamp,
    /// `jmemmgr.c:753-762`), even one below the 1024-byte footprint.
    ShortProgressive,
}

thread_local! {
    static FIRED: Cell<bool> = const { Cell::new(false) };
    static MSG_CODE: Cell<c_int> = const { Cell::new(0) };
}

/// Records the first failure; the harness checks after every stage and
/// stops, the control flow the C oracle's `setjmp` gives it.
unsafe extern "C" fn recording_error_exit(cinfo: *mut c_void) {
    // SAFETY: the error path reads only the leading `err` pointer.
    unsafe {
        let err_ptr: *mut JpegErrorMgr = (cinfo as *const *mut JpegErrorMgr).read();
        if FIRED.with(|f| f.get()) {
            return;
        }
        FIRED.with(|f| f.set(true));
        MSG_CODE.with(|c| c.set(std::ptr::addr_of!((*err_ptr).msg_code).read()));
    }
}

/// An in-memory grayscale JPEG through the shim's own classic compress,
/// mirroring the oracle's `make_source` shape for shape.
fn make_gray_source(progressive: bool, width: usize, height: usize) -> Vec<u8> {
    let mut err: JpegErrorMgr = unsafe { std::mem::zeroed() };
    let mut cinfo: Box<JpegCompressPublic> = Box::new(unsafe { std::mem::zeroed() });
    let cinfo_ptr: *mut c_void = &mut *cinfo as *mut JpegCompressPublic as *mut c_void;
    let mut buf: *mut u8 = std::ptr::null_mut();
    let mut size: std::ffi::c_ulong = 0;

    // SAFETY: the classic sequence over a zeroed mirror; buffers are locals.
    unsafe {
        cinfo.err = jpeg_std_error(&mut err);
        libjpeg_turbo_rs_capi::jpeglib::jpeg_create_compress(cinfo_ptr);
        jpeg_mem_dest(cinfo_ptr, &mut buf, &mut size);
        cinfo.image_width = width as u32;
        cinfo.image_height = height as u32;
        cinfo.input_components = 1;
        cinfo.in_color_space = JCS_GRAYSCALE;
        jpeg_set_defaults(cinfo_ptr);
        if progressive {
            jpeg_simple_progression(cinfo_ptr);
        }
        jpeg_start_compress(cinfo_ptr, 1);
        let mut row: Vec<u8> = vec![0; width];
        for r in 0..height {
            for (i, b) in row.iter_mut().enumerate() {
                *b = ((r * 7 + i * 13) & 0xFF) as u8;
            }
            let mut rows: [*mut u8; 1] = [row.as_mut_ptr()];
            let _ = jpeg_write_scanlines(cinfo_ptr, rows.as_mut_ptr(), 1);
        }
        jpeg_finish_compress(cinfo_ptr);
        let out: Vec<u8> = std::slice::from_raw_parts(buf, size as usize).to_vec();
        jpeg_destroy_compress(cinfo_ptr);
        extern "C" {
            fn free(p: *mut c_void);
        }
        free(buf as *mut c_void);
        out
    }
}

fn make_source(kind: SrcKind) -> Vec<u8> {
    match kind {
        SrcKind::Baseline => make_gray_source(false, 64, 64),
        SrcKind::Progressive => make_gray_source(true, 64, 64),
        SrcKind::Mss => MSS_FIXTURE.to_vec(),
        SrcKind::BigProgressive => make_gray_source(true, 1024, 1024),
        SrcKind::ShortProgressive => make_gray_source(true, 64, 8),
    }
}

/// One decode case in the oracle's exact line format: `case stage code`.
fn run_case(label: &str, kind: SrcKind, budget: c_long, buffered: bool) -> String {
    FIRED.with(|f| f.set(false));
    MSG_CODE.with(|c| c.set(0));

    let src: Vec<u8> = make_source(kind);
    let mut err: JpegErrorMgr = unsafe { std::mem::zeroed() };
    let mut cinfo: Box<JpegDecompressPublic> = Box::new(unsafe { std::mem::zeroed() });
    let cinfo_ptr: *mut c_void = &mut *cinfo as *mut JpegDecompressPublic as *mut c_void;

    let fired = || FIRED.with(|f| f.get());
    let line = |stage: &str| format!("{label} {stage} {}\n", MSG_CODE.with(|c| c.get()));

    // SAFETY: the documented classic decode sequence over a zeroed mirror.
    unsafe {
        let errp: *mut JpegErrorMgr = jpeg_std_error(&mut err);
        (*errp).error_exit = Some(recording_error_exit);
        cinfo.err = errp;
        libjpeg_turbo_rs_capi::jpeglib::jpeg_CreateDecompress(
            cinfo_ptr,
            80,
            std::mem::size_of::<JpegDecompressPublic>(),
        );
        jpeg_mem_src(cinfo_ptr, src.as_ptr(), src.len() as std::ffi::c_ulong);

        let _ = jpeg_read_header(cinfo_ptr, 1);
        if fired() {
            let out: String = line("header");
            jpeg_destroy_decompress(cinfo_ptr);
            return out;
        }

        // The caller sets the field after create/header, as libjpeg.txt
        // documents; this is the sequence #467 names.
        std::ptr::addr_of_mut!((*(cinfo.mem as *mut JpegMemoryMgr)).max_memory_to_use)
            .write(budget);
        if buffered {
            cinfo.buffered_image = 1;
        }

        let _ = jpeg_start_decompress(cinfo_ptr);
        if fired() {
            let out: String = line("start");
            jpeg_destroy_decompress(cinfo_ptr);
            return out;
        }

        let mut row: Vec<u8> = vec![0; 4096 * 4];
        if buffered {
            // The documented buffered-image loop (libjpeg.txt), with a pass
            // cap so a shim bug fails the test instead of hanging it.
            let mut passes: u32 = 0;
            loop {
                passes += 1;
                assert!(
                    passes <= 64,
                    "{label}: buffered-image loop did not converge"
                );
                let _ = jpeg_start_output(cinfo_ptr, cinfo.input_scan_number);
                if fired() {
                    let out: String = line("scan");
                    jpeg_destroy_decompress(cinfo_ptr);
                    return out;
                }
                // `loop` + explicit break: `jpeg_read_scanlines` advances
                // `output_scanline` through the raw pointer, which clippy's
                // `while_immutable_condition` cannot see.
                loop {
                    if cinfo.output_scanline >= cinfo.output_height {
                        break;
                    }
                    let mut rows: [*mut u8; 1] = [row.as_mut_ptr()];
                    let got: u32 = jpeg_read_scanlines(cinfo_ptr, rows.as_mut_ptr(), 1);
                    if fired() {
                        let out: String = line("scan");
                        jpeg_destroy_decompress(cinfo_ptr);
                        return out;
                    }
                    if got == 0 {
                        break;
                    }
                }
                let _ = jpeg_finish_output(cinfo_ptr);
                if fired() {
                    let out: String = line("scan");
                    jpeg_destroy_decompress(cinfo_ptr);
                    return out;
                }
                if jpeg_input_complete(cinfo_ptr) != 0 {
                    break;
                }
            }
        } else {
            // Same `loop` shape as above, for the same clippy reason.
            loop {
                if cinfo.output_scanline >= cinfo.output_height {
                    break;
                }
                let mut rows: [*mut u8; 1] = [row.as_mut_ptr()];
                let got: u32 = jpeg_read_scanlines(cinfo_ptr, rows.as_mut_ptr(), 1);
                if fired() {
                    let out: String = line("scan");
                    jpeg_destroy_decompress(cinfo_ptr);
                    return out;
                }
                if got == 0 {
                    break;
                }
            }
        }
        let _ = jpeg_finish_decompress(cinfo_ptr);
        let out: String = if fired() {
            line("scan")
        } else {
            format!("{label} ok 0\n")
        };
        jpeg_destroy_decompress(cinfo_ptr);
        out
    }
}

/// `jpeg_has_multiple_scans()` after `jpeg_read_header`, in the oracle's
/// `label value` format.
fn hms_line(label: &str, kind: SrcKind) -> String {
    FIRED.with(|f| f.set(false));
    MSG_CODE.with(|c| c.set(0));

    let src: Vec<u8> = make_source(kind);
    let mut err: JpegErrorMgr = unsafe { std::mem::zeroed() };
    let mut cinfo: Box<JpegDecompressPublic> = Box::new(unsafe { std::mem::zeroed() });
    let cinfo_ptr: *mut c_void = &mut *cinfo as *mut JpegDecompressPublic as *mut c_void;

    // SAFETY: header parse only, over a zeroed mirror.
    unsafe {
        let errp: *mut JpegErrorMgr = jpeg_std_error(&mut err);
        (*errp).error_exit = Some(recording_error_exit);
        cinfo.err = errp;
        libjpeg_turbo_rs_capi::jpeglib::jpeg_CreateDecompress(
            cinfo_ptr,
            80,
            std::mem::size_of::<JpegDecompressPublic>(),
        );
        jpeg_mem_src(cinfo_ptr, src.as_ptr(), src.len() as std::ffi::c_ulong);
        let _ = jpeg_read_header(cinfo_ptr, 1);
        let out: String = if FIRED.with(|f| f.get()) {
            format!("{label} parse_failed {}\n", MSG_CODE.with(|c| c.get()))
        } else {
            format!(
                "{label} {}\n",
                if jpeg_has_multiple_scans(cinfo_ptr) != 0 {
                    1
                } else {
                    0
                }
            )
        };
        jpeg_destroy_decompress(cinfo_ptr);
        out
    }
}

/// Issue #467 (P4-14): the full case matrix, stage + `msg_code`, compared
/// verbatim against stock libjpeg.
#[test]
fn classic_decode_budget_matches_stock_libjpeg() {
    let Some(oracle) = helpers::build_classic_oracle("classic_budget_oracle") else {
        eprintln!(
            "SKIP: no classic libjpeg development install found; set \
             LIBJPEG_TURBO_PREFIX to make this a hard failure."
        );
        return;
    };
    let c_trace: String = helpers::run_oracle(&oracle, &[]);

    const MIB: c_long = 1024 * 1024;
    let mut ours: String = String::new();
    ours.push_str(&run_case("baseline_unlimited", SrcKind::Baseline, 0, false));
    ours.push_str(&run_case("baseline_tiny", SrcKind::Baseline, 1000, false));
    ours.push_str(&run_case(
        "baseline_generous",
        SrcKind::Baseline,
        100 * MIB,
        false,
    ));
    ours.push_str(&run_case(
        "progressive_unlimited",
        SrcKind::Progressive,
        0,
        false,
    ));
    ours.push_str(&run_case(
        "progressive_tiny",
        SrcKind::Progressive,
        1000,
        false,
    ));
    ours.push_str(&run_case(
        "progressive_generous",
        SrcKind::Progressive,
        100 * MIB,
        false,
    ));
    ours.push_str(&run_case("mss_tiny", SrcKind::Mss, 1000, false));
    ours.push_str(&run_case("mss_generous", SrcKind::Mss, 100 * MIB, false));
    ours.push_str(&run_case(
        "buffered_baseline_tiny",
        SrcKind::Baseline,
        1000,
        true,
    ));
    ours.push_str(&run_case(
        "buffered_baseline_generous",
        SrcKind::Baseline,
        100 * MIB,
        true,
    ));
    ours.push_str(&run_case(
        "big_progressive_tight",
        SrcKind::BigProgressive,
        MIB,
        false,
    ));
    ours.push_str(&run_case(
        "big_progressive_midband",
        SrcKind::BigProgressive,
        4 * MIB,
        false,
    ));
    ours.push_str(&run_case(
        "short_progressive_tiny",
        SrcKind::ShortProgressive,
        1000,
        false,
    ));
    ours.push_str(&hms_line("hms_baseline", SrcKind::Baseline));
    ours.push_str(&hms_line("hms_progressive", SrcKind::Progressive));
    ours.push_str(&hms_line("hms_mss", SrcKind::Mss));

    assert_eq!(
        ours, c_trace,
        "classic max_memory_to_use enforcement diverges from stock libjpeg \
         (P4-14, #467)"
    );
}

/// The budget refusal itself, independent of any C oracle. Expectations are
/// the stock measurements baked into the oracle's comment block: every
/// multi-scan or buffered stream refuses a tiny budget at
/// `jpeg_start_decompress` with `JERR_NO_BACKING_STORE`; baseline is never
/// bounded; and a budget above the coefficient-array bytes accepts even
/// when a whole-pipeline estimate would not (the e492da9 regression).
#[test]
fn budget_refusal_fires_standalone() {
    let refusal = |label: &str| format!("{label} start {JERR_NO_BACKING_STORE}\n");

    assert_eq!(
        run_case("p", SrcKind::Progressive, 1000, false),
        refusal("p"),
        "a 1000-byte budget must refuse a progressive decode at start"
    );
    assert_eq!(
        run_case("m", SrcKind::Mss, 1000, false),
        refusal("m"),
        "multi-scan sequential realizes whole-image coefficient arrays \
         upstream (has_multiple_scans, jdinput.c:153-156) — a tiny budget \
         must refuse it even though progressive_mode is FALSE"
    );
    assert_eq!(
        run_case("bb", SrcKind::Baseline, 1000, true),
        refusal("bb"),
        "buffered-image mode realizes whole-image arrays for any stream \
         (jdmaster.c:709) — a tiny budget must refuse even baseline"
    );
    assert_eq!(
        run_case("b", SrcKind::Baseline, 1000, false),
        "b ok 0\n",
        "baseline needs no whole-image coefficient arrays — stock accepts it \
         under the same budget, and so must we"
    );
    assert_eq!(
        run_case("g", SrcKind::Progressive, 100 * 1024 * 1024, false),
        "g ok 0\n"
    );
    // 1024×1024 gray progressive holds exactly 2 MiB of coefficient
    // blocks (128×128 blocks × 128 bytes). 4 MiB must ACCEPT: upstream
    // counts only the coefficient arrays, and stock accepts this decode
    // (measured; a whole-pipeline estimate refused it — review of
    // e492da9).
    assert_eq!(
        run_case("mid", SrcKind::BigProgressive, 4 * 1024 * 1024, false),
        "mid ok 0\n",
        "a budget above the coefficient-array bytes must accept: upstream \
         counts only what realize_virt_arrays realizes"
    );
    assert_eq!(
        run_case("tight", SrcKind::BigProgressive, 1024 * 1024, false),
        refusal("tight")
    );
    // 64×8 gray progressive: every coefficient array fits one access
    // window (maxaccess = v_samp × 5 for progressive, jdcoefct.c:897-901),
    // and realize_virt_arrays clamps max_minheights to >= 1
    // (jmemmgr.c:753-762) — upstream realizes it in full at ANY positive
    // budget. 1000 bytes is below the 1024-byte coefficient footprint, so
    // a pure footprint-vs-budget model wrongly refuses this (measured:
    // stock accepts even a 1-byte budget for this class).
    assert_eq!(
        run_case("short", SrcKind::ShortProgressive, 1000, false),
        "short ok 0\n",
        "a stream whose arrays all fit one access window must accept any \
         positive budget, as stock does"
    );
}

/// `jpeg_has_multiple_scans` must reflect upstream's definition —
/// `(comps_in_scan < num_components) || progressive_mode`
/// (`jdinput.c:153-156`) — not `progressive_mode` alone. The fixture is
/// SOF0 with three single-component scans: multiple scans, not
/// progressive.
#[test]
fn has_multiple_scans_reports_non_interleaved_sequential() {
    assert_eq!(hms_line("h", SrcKind::Baseline), "h 0\n");
    assert_eq!(hms_line("h", SrcKind::Progressive), "h 1\n");
    assert_eq!(hms_line("h", SrcKind::Mss), "h 1\n");
}
