#!/usr/bin/env bash
# FFI B9-4: Build stock djpeg/cjpeg/jpegtran from references/libjpeg-turbo/src/
# sources, link against OUR cdylib (libjpeg_turbo_rs_capi), not the stock
# libjpeg-turbo build.
#
# Output: $OUT_DIR/{djpeg,cjpeg,jpegtran} linked to our libjpeg.so.62 /
# libjpeg.62.dylib (via -l:libjpeg_turbo_rs_capi... on linux, -install_name
# rewriting on macOS).
#
# Exit 0 on success. On link failure, the cc invocation's stderr (including
# missing-symbol list) is preserved at $OUT_DIR/link_errors.txt so
# capi_stock_tool_link.rs can surface it as a test assertion failure that
# documents the gap.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/../.." &> /dev/null && pwd)"
REF_SRC="$REPO_ROOT/references/libjpeg-turbo/src"
OUT_DIR="${OUT_DIR:-$SCRIPT_DIR/build}"
CAPI_TARGET_DIR="${CAPI_TARGET_DIR:-$REPO_ROOT/target/release}"

mkdir -p "$OUT_DIR"
: > "$OUT_DIR/link_errors.txt"

# Detect our shim's filename (platform-dependent).
case "$(uname -s)" in
    Darwin)
        SHIM_LIB="$CAPI_TARGET_DIR/liblibjpeg_turbo_rs_capi.dylib"
        LIB_EXT="dylib"
        ;;
    Linux)
        SHIM_LIB="$CAPI_TARGET_DIR/liblibjpeg_turbo_rs_capi.so"
        LIB_EXT="so"
        ;;
    *)
        echo "ERROR: unsupported host OS: $(uname -s)" >&2
        exit 2
        ;;
esac

if [[ ! -f "$SHIM_LIB" ]]; then
    echo "ERROR: shim cdylib not found at $SHIM_LIB" >&2
    echo "       Build it first: cargo build -p libjpeg-turbo-rs-capi --release" >&2
    exit 3
fi

# Common include path: the stock jpeglib.h header, required because
# djpeg.c / cjpeg.c / jpegtran.c all #include <jpeglib.h> and several
# private headers. jconfig.h / jconfigint.h are generated by cmake in a
# real build; here we check the submodule's cmake output dir, then fall
# back to a minimal hand-rolled jconfig.h.
if [[ -d "$REPO_ROOT/references/libjpeg-turbo/build" ]]; then
    CONFIG_INC="-I$REPO_ROOT/references/libjpeg-turbo/build -I$REPO_ROOT/references/libjpeg-turbo"
else
    # Emit a minimal jconfig.h / jconfigint.h pair into $OUT_DIR so the
    # sources compile even without a prior cmake invocation.
    cat > "$OUT_DIR/jconfig.h" <<'EOF'
/* Minimal jconfig.h for stock_djpeg_cjpeg build. Mirrors a 64-bit Linux /
 * macOS x86_64 / aarch64 host; no dependency on libpng / zlib. */
#define JPEG_LIB_VERSION 80
#define LIBJPEG_TURBO_VERSION 3.1.2
#define LIBJPEG_TURBO_VERSION_NUMBER 3001002
#define BITS_IN_JSAMPLE 8
#define HAVE_STDLIB_H 1
#define HAVE_STDDEF_H 1
#define HAVE_UNSIGNED_CHAR 1
#define HAVE_UNSIGNED_SHORT 1
#define MEM_SRCDST_SUPPORTED 1
#define C_ARITH_CODING_SUPPORTED 1
#define D_ARITH_CODING_SUPPORTED 1
#define WITH_SIMD 0
EOF
    cat > "$OUT_DIR/jconfigint.h" <<'EOF'
#define BUILD "0"
#define HIDDEN __attribute__((visibility("hidden")))
#define INLINE inline __attribute__((always_inline))
#define PACKAGE_NAME "libjpeg-turbo"
#define VERSION "3.1.2"
#define SIZEOF_SIZE_T 8
#define THREAD_LOCAL __thread
#define FALLTHROUGH __attribute__((fallthrough));
#define FORCE_INLINE static INLINE
EOF
    CONFIG_INC="-I$OUT_DIR -I$REF_SRC -I$REPO_ROOT/references/libjpeg-turbo"
fi

CC="${CC:-cc}"
CFLAGS_COMMON="-O2 -Wno-unused -Wno-deprecated-declarations $CONFIG_INC -I$REF_SRC -I$REPO_ROOT/references/libjpeg-turbo"

# Object files shared by djpeg/cjpeg/jpegtran. These are the libjpeg-turbo
# "application helper" sources that live alongside the CLI tool sources —
# NOT part of libjpeg.so itself. They must be compiled into each tool.
CDJPEG_SRCS=(
    "$REF_SRC/cdjpeg.c"
    "$REF_SRC/rdswitch.c"
    "$REF_SRC/rdjpgcom.c"
)

DJPEG_SRCS=(
    "$REF_SRC/djpeg.c"
    "$REF_SRC/wrppm.c"
    "$REF_SRC/wrbmp.c"
    "$REF_SRC/wrtarga.c"
    "$REF_SRC/wrgif.c"
    "$REF_SRC/rdcolmap.c"
    "${CDJPEG_SRCS[@]}"
)

CJPEG_SRCS=(
    "$REF_SRC/cjpeg.c"
    "$REF_SRC/rdppm.c"
    "$REF_SRC/rdbmp.c"
    "$REF_SRC/rdtarga.c"
    "$REF_SRC/rdgif.c"
    "${CDJPEG_SRCS[@]}"
)

JPEGTRAN_SRCS=(
    "$REF_SRC/jpegtran.c"
    "$REF_SRC/transupp.c"
    "${CDJPEG_SRCS[@]}"
)

# Link args: point at our shim. On macOS we must strip the "liblib"
# prefix artifact by using the full path + -Wl,-install_name fix-up at
# the binary level (done later via install_name_tool).
LINK_ARGS=("$SHIM_LIB")
if [[ "$LIB_EXT" == "so" ]]; then
    LINK_ARGS+=("-Wl,-rpath,$CAPI_TARGET_DIR")
fi

build_one() {
    local name="$1"; shift
    local srcs=("$@")
    local out="$OUT_DIR/$name"
    local log="$OUT_DIR/${name}_build.log"
    echo "==> Building $name -> $out" >&2
    if ! "$CC" $CFLAGS_COMMON -o "$out" "${srcs[@]}" "${LINK_ARGS[@]}" 2> "$log"; then
        echo "LINK FAILED: $name" | tee -a "$OUT_DIR/link_errors.txt"
        cat "$log" | tee -a "$OUT_DIR/link_errors.txt"
        echo "----" >> "$OUT_DIR/link_errors.txt"
        return 1
    fi
    return 0
}

FAILED=0
build_one djpeg    "${DJPEG_SRCS[@]}"    || FAILED=1
build_one cjpeg    "${CJPEG_SRCS[@]}"    || FAILED=1
build_one jpegtran "${JPEGTRAN_SRCS[@]}" || FAILED=1

if (( FAILED )); then
    echo "One or more stock tool links failed. See $OUT_DIR/link_errors.txt" >&2
    exit 4
fi

# macOS: fix the install_name so the tool finds our .dylib at runtime.
if [[ "$LIB_EXT" == "dylib" ]]; then
    for t in djpeg cjpeg jpegtran; do
        install_name_tool -change "@rpath/libjpeg.62.dylib" "$SHIM_LIB" "$OUT_DIR/$t" 2>/dev/null || true
    done
fi

echo "OK: stock tools built and linked to $SHIM_LIB" >&2
