#!/usr/bin/env bash
# install_capi.sh — stage `libjpeg-turbo-rs-capi`'s cdylib + headers +
# pkg-config + CMake config into a DESTDIR/PREFIX tree the way
# distro packagers expect.
#
# This is the P2-8 install path: it produces the layout that
# `pkg-config --libs libjpeg`, `find_package(JPEG)`, and consumers like
# Pillow / ImageMagick / libvips expect when our cdylib is dropped in
# place of upstream `libjpeg.so.8` / `libturbojpeg.so.0`. The default
# tracks the build.rs default (P4-3, 2026-05-17): v8 ABI / `libjpeg.so.8`
# / `@rpath/libjpeg.8.dylib`. v6b is an explicit opt-in.
#
# Usage:
#   scripts/install_capi.sh --destdir /tmp/install --prefix /usr
#
# Required env vs CLI flags (CLI wins):
#   --destdir DIR     Stage root (defaults to "")
#   --prefix DIR      Install prefix (defaults to "/usr/local")
#   --soname NAME     libjpeg "major" SONAME on Linux (default
#                     "libjpeg.so.8"; pass "libjpeg.so.62" to opt into
#                     the v6b SONAME — docs/ABI_COMPATIBILITY.md flags
#                     v6b as the documented-risk path for v8-layout
#                     consumers). On macOS, accepts the compat dylib name
#                     (default "libjpeg.8.dylib"). The real cdylib
#                     filename is derived as
#                     "${soname}.${version}" (Linux) or
#                     "${soname%.dylib}.${version}.dylib" (macOS).
#   --soname-tj NAME  libturbojpeg "major" SONAME (default
#                     "libturbojpeg.so.0" / "libturbojpeg.0.dylib").
#   --build           Force a cdylib build. Without it, a missing cdylib is
#                     still built automatically.
#   CAPI_TARGET_DIR   Exact target-qualified Cargo release directory containing
#                     the cdylib. Relative paths use `$ROOT`. With `--build`,
#                     it must end in `/<target-triple>/release` so Cargo can
#                     derive its target root. Defaults below CARGO_TARGET_DIR
#                     (or `$ROOT/target`) using CAPI_BUILD_TARGET.
#   CAPI_BUILD_TARGET Cargo target passed explicitly to nested builds. Defaults
#                     to CARGO_BUILD_TARGET when set, otherwise Cargo's host.
#
# Layout produced under ${DESTDIR}${PREFIX} (defaults — v8):
#   lib/libjpeg.so.8.X.Y           actual cdylib
#   lib/libjpeg.so.8               symlink → .X.Y
#   lib/libjpeg.so                 symlink → libjpeg.so.8
#   lib/libturbojpeg.so.0.X.Y      hardlink/copy of the cdylib
#   lib/libturbojpeg.so.0          symlink → .X.Y
#   lib/libturbojpeg.so            symlink → libturbojpeg.so.0
#   lib/pkgconfig/libjpeg.pc       generated by build.rs (re-staged here)
#   lib/pkgconfig/libturbojpeg.pc  generated by build.rs (re-staged here)
#   lib/cmake/JPEG/JPEGConfig.cmake  CMake `find_package(JPEG)` shim
#   include/jpeglib.h              from references/libjpeg-turbo/src/
#   include/jerror.h               from references/libjpeg-turbo/src/
#   include/jmorecfg.h             from references/libjpeg-turbo/src/
#   include/jconfig.h              generated (matches build.rs's v8 defaults)
#   include/turbojpeg.h            from references/libjpeg-turbo/src/

set -euo pipefail

DESTDIR=""
PREFIX="/usr/local"
SONAME=""
SONAME_TJ=""
DO_BUILD=0
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CARGO_BIN="${CARGO:-cargo}"

resolve_build_target() {
    if [[ -n "${CAPI_BUILD_TARGET:-}" ]]; then
        printf '%s\n' "$CAPI_BUILD_TARGET"
    elif [[ -n "${CARGO_BUILD_TARGET:-}" ]]; then
        printf '%s\n' "$CARGO_BUILD_TARGET"
    else
        "$CARGO_BIN" -vV | sed -n 's/^host: //p'
    fi
}

target_component() {
    local target="$1"
    basename "${target%.json}"
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --destdir)    DESTDIR="$2"; shift 2 ;;
        --prefix)     PREFIX="$2"; shift 2 ;;
        --soname)     SONAME="$2"; shift 2 ;;
        --soname-tj)  SONAME_TJ="$2"; shift 2 ;;
        --build)      DO_BUILD=1; shift ;;
        --root)       ROOT="$2"; shift 2 ;;
        -h|--help)
            sed -n '2,/^set -euo/p' "$0" | sed 's/^# *//'
            exit 0
            ;;
        *) echo "unknown arg: $1" >&2; exit 1 ;;
    esac
done

OS_NAME="$(uname -s)"
case "$OS_NAME" in
    Linux*)  PLATFORM=linux ;;
    Darwin*) PLATFORM=macos ;;
    *) echo "unsupported platform: $OS_NAME" >&2; exit 1 ;;
esac

BUILD_TARGET=""
case "${CAPI_TARGET_DIR:-}" in
    "")
        BUILD_TARGET="$(resolve_build_target)"
        [[ -n "$BUILD_TARGET" ]] || { echo "could not resolve Cargo build target" >&2; exit 1; }
        case "${CARGO_TARGET_DIR:-}" in
            "")  CARGO_TARGET_ROOT="$ROOT/target" ;;
            /*)  CARGO_TARGET_ROOT="$CARGO_TARGET_DIR" ;;
            *)   CARGO_TARGET_ROOT="$ROOT/$CARGO_TARGET_DIR" ;;
        esac
        RELEASE_DIR="$CARGO_TARGET_ROOT/$(target_component "$BUILD_TARGET")/release"
        ;;
    /*)  RELEASE_DIR="$CAPI_TARGET_DIR" ;;
    *)   RELEASE_DIR="$ROOT/$CAPI_TARGET_DIR" ;;
esac

# Resolve cdylib path + version from Cargo.toml.
CDYLIB_VERSION="$(grep '^version' "$ROOT/crates/libjpeg-turbo-rs-capi/Cargo.toml" | head -1 | sed 's/.*"\(.*\)".*/\1/')"
case "$PLATFORM" in
    linux)
        CDYLIB_FILE="$RELEASE_DIR/liblibjpeg_turbo_rs_capi.so"
        # P4-3 (2026-05-17): default flipped from libjpeg.so.62 → libjpeg.so.8
        # to match the build.rs SONAME default and the v8 struct layout.
        DEFAULT_LIBJPEG_MAJOR="libjpeg.so.8"
        DEFAULT_LIBJPEG_DEV="libjpeg.so"
        DEFAULT_LIBTJ_MAJOR="libturbojpeg.so.0"
        DEFAULT_LIBTJ_DEV="libturbojpeg.so"
        ;;
    macos)
        CDYLIB_FILE="$RELEASE_DIR/liblibjpeg_turbo_rs_capi.dylib"
        # P4-3 (2026-05-17): default flipped from libjpeg.62.dylib → libjpeg.8.dylib
        # to match the build.rs install_name default and the v8 struct layout.
        DEFAULT_LIBJPEG_MAJOR="libjpeg.8.dylib"
        DEFAULT_LIBJPEG_DEV="libjpeg.dylib"
        DEFAULT_LIBTJ_MAJOR="libturbojpeg.0.dylib"
        DEFAULT_LIBTJ_DEV="libturbojpeg.dylib"
        ;;
esac

# Honor --soname / --soname-tj overrides.
LIBJPEG_MAJOR="${SONAME:-$DEFAULT_LIBJPEG_MAJOR}"
LIBTJ_MAJOR="${SONAME_TJ:-$DEFAULT_LIBTJ_MAJOR}"

# Derive the real (versioned) cdylib filename from the major SONAME.
# Linux: append .${VERSION} (e.g. libjpeg.so.8 → libjpeg.so.8.X.Y).
# macOS: insert ${VERSION} before the .dylib suffix (e.g. libjpeg.8.dylib
#        → libjpeg.8.X.Y.dylib).
# Derive the bare dev-link filename: drop everything from the SONAME
# digit onward (Linux) or the major digit before .dylib (macOS) so
# packagers passing a non-default --soname still get a sensible
# `libjpeg.{so,dylib}` symlink at the top of the chain.
case "$PLATFORM" in
    linux)
        LIBJPEG_REAL="${LIBJPEG_MAJOR}.${CDYLIB_VERSION}"
        LIBTJ_REAL="${LIBTJ_MAJOR}.${CDYLIB_VERSION}"
        # Strip everything after `.so` to get the dev link.
        LIBJPEG_DEV="${LIBJPEG_MAJOR%%.so*}.so"
        LIBTJ_DEV="${LIBTJ_MAJOR%%.so*}.so"
        ;;
    macos)
        LIBJPEG_REAL="${LIBJPEG_MAJOR%.dylib}.${CDYLIB_VERSION}.dylib"
        LIBTJ_REAL="${LIBTJ_MAJOR%.dylib}.${CDYLIB_VERSION}.dylib"
        # Strip the version digits before .dylib to get the dev link.
        # `libjpeg.62.dylib` → `libjpeg.dylib`.
        LIBJPEG_DEV="$(echo "$LIBJPEG_MAJOR" | sed 's/\.[0-9][0-9]*\.dylib$/.dylib/')"
        LIBTJ_DEV="$(echo "$LIBTJ_MAJOR" | sed 's/\.[0-9][0-9]*\.dylib$/.dylib/')"
        ;;
esac

# Replace the now-unused defaults with the resolved names so the
# install/symlink steps below pick them up.
DEFAULT_LIBJPEG_REAL="$LIBJPEG_REAL"
DEFAULT_LIBJPEG_MAJOR="$LIBJPEG_MAJOR"
DEFAULT_LIBJPEG_DEV="$LIBJPEG_DEV"
DEFAULT_LIBTJ_REAL="$LIBTJ_REAL"
DEFAULT_LIBTJ_MAJOR="$LIBTJ_MAJOR"
DEFAULT_LIBTJ_DEV="$LIBTJ_DEV"

if [[ "$DO_BUILD" -eq 1 || ! -f "$CDYLIB_FILE" ]]; then
    BUILD_TARGET="${BUILD_TARGET:-$(resolve_build_target)}"
    [[ -n "$BUILD_TARGET" ]] || { echo "could not resolve Cargo build target" >&2; exit 1; }
    TARGET_COMPONENT="$(target_component "$BUILD_TARGET")"
    if [[ "$(basename "$RELEASE_DIR")" != "release" ||
          "$(basename "$(dirname "$RELEASE_DIR")")" != "$TARGET_COMPONENT" ]]; then
        echo "CAPI_TARGET_DIR must end in /${TARGET_COMPONENT}/release when building: $RELEASE_DIR" >&2
        exit 1
    fi
    CARGO_TARGET_ROOT="$(dirname "$(dirname "$RELEASE_DIR")")"
    (cd "$ROOT" && CARGO_TARGET_DIR="$CARGO_TARGET_ROOT" \
        "$CARGO_BIN" build -p libjpeg-turbo-rs-capi --release --target "$BUILD_TARGET")
fi
[[ -f "$CDYLIB_FILE" ]] || { echo "cdylib not found: $CDYLIB_FILE" >&2; exit 1; }

# ---------------------------------------------------------------------------
# P4-81: GNU symbol versions on the shipped ELF library.
#
# The cdylib cargo produces cannot carry them. rustc passes its own version
# script for every cdylib -- an *anonymous* tag, `{ global: ...; local: *; };`
# -- and GNU ld refuses to combine an anonymous version tag with named ones,
# so adding `LIBJPEG_8.0` as a second script fails the link outright with
# `anonymous version tag cannot be combined with other version tags`. Verified
# against binutils 2.47 across every script surface, including `.symver`, which
# fails differently (`version node not found`) because it attaches a symbol to
# a node without defining one. rustc exposes no knob to suppress its script.
#
# The one configuration that works is a single named script carrying `local: *`
# itself -- so whoever owns the link owns the versioning. Here we do: relink the
# shipped library from the staticlib the crate already builds.
#
# Policy mirrors the test-suite rule (P4-116): a missing prerequisite is
# environmental and degrades with a loud warning, but a relink we *attempt* and
# that fails is a defect and stops the install rather than silently shipping an
# unversioned library that callers believe is versioned.
# ---------------------------------------------------------------------------
JPEG_LIB_SOURCE="$CDYLIB_FILE"
if [[ "$PLATFORM" == "linux" && "${CAPI_SKIP_SYMBOL_VERSIONS:-0}" != "1" ]]; then
    if [[ "$LIBJPEG_MAJOR" != libjpeg.so.8* ]]; then
        echo "note: SONAME '${LIBJPEG_MAJOR}' is not the v8 identity; shipping without symbol versions (P4-81)" >&2
    else
        VERSION_MAP="$(find "$RELEASE_DIR/build" -type f -name libjpeg.map 2>/dev/null | head -1)"
        STATIC_LIB="$RELEASE_DIR/liblibjpeg_turbo_rs_capi.a"
        CC_BIN="${CC:-cc}"
        if [[ -z "$VERSION_MAP" || ! -f "$STATIC_LIB" ]] || ! command -v "$CC_BIN" >/dev/null 2>&1; then
            echo "warning: cannot add GNU symbol versions (map='${VERSION_MAP:-missing}', staticlib='${STATIC_LIB}', cc='${CC_BIN}')." >&2
            echo "         Shipping the unversioned cdylib; prebuilt consumers will see 'no version information available' (P4-81)." >&2
        else
            VERSIONED_LIB="${RELEASE_DIR}/${LIBJPEG_MAJOR}.${CDYLIB_VERSION}.versioned"
            # --whole-archive: nothing references the `#[no_mangle]` exports, so
            #   without it the linker drops the entire archive.
            # --allow-multiple-definition: Rust staticlibs bundle compiler_builtins
            #   symbols that also arrive from libgcc.
            if ! "$CC_BIN" -shared -o "$VERSIONED_LIB" \
                    -Wl,--whole-archive "$STATIC_LIB" -Wl,--no-whole-archive \
                    -Wl,--version-script,"$VERSION_MAP" \
                    -Wl,-soname,"$LIBJPEG_MAJOR" \
                    -Wl,--allow-multiple-definition \
                    -lpthread -ldl -lm; then
                echo "ERROR: relinking ${LIBJPEG_MAJOR} with ${VERSION_MAP} failed." >&2
                echo "       Set CAPI_SKIP_SYMBOL_VERSIONS=1 to install the unversioned cdylib instead." >&2
                exit 1
            fi
            JPEG_LIB_SOURCE="$VERSIONED_LIB"
            echo "P4-81: relinked ${LIBJPEG_MAJOR} from the staticlib with GNU symbol versions"
        fi
    fi
fi

# Stage roots.
LIBDIR="${DESTDIR}${PREFIX}/lib"
INCDIR="${DESTDIR}${PREFIX}/include"
PKGCFGDIR="${LIBDIR}/pkgconfig"
CMAKEDIR="${LIBDIR}/cmake/JPEG"
mkdir -p "$LIBDIR" "$INCDIR" "$PKGCFGDIR" "$CMAKEDIR"

# Install cdylib + symlink chains.
install -m 0755 "$JPEG_LIB_SOURCE" "${LIBDIR}/${DEFAULT_LIBJPEG_REAL}"
ln -sf "$DEFAULT_LIBJPEG_REAL" "${LIBDIR}/${DEFAULT_LIBJPEG_MAJOR}"
ln -sf "$DEFAULT_LIBJPEG_MAJOR" "${LIBDIR}/${DEFAULT_LIBJPEG_DEV}"
# libturbojpeg shares the same binary (we export both APIs).
# Same binary: our map has no catch-all node, so the tj* surface stays
# unversioned exactly as before (P4-81).
install -m 0755 "$JPEG_LIB_SOURCE" "${LIBDIR}/${DEFAULT_LIBTJ_REAL}"
ln -sf "$DEFAULT_LIBTJ_REAL" "${LIBDIR}/${DEFAULT_LIBTJ_MAJOR}"
ln -sf "$DEFAULT_LIBTJ_MAJOR" "${LIBDIR}/${DEFAULT_LIBTJ_DEV}"

# Rewrite each installed cdylib's identity (macOS install_name /
# Linux DT_SONAME) so it matches the SONAME the script was told
# about. Without this, `--soname libjpeg.so.62` (or its macOS twin
# `libjpeg.62.dylib`) would stage a v6b symlink chain but leave the
# cdylib advertising the build-time identity (typically `libjpeg.so.8`
# / `@rpath/libjpeg.8.dylib`), and the dynamic linker would refuse to
# load it under the v6b name — or, on Linux, a downstream linked
# against `-ljpeg` would record `libjpeg.so.8` in its DT_NEEDED
# instead of `libjpeg.so.62`, so `ldd` would resolve to the wrong
# file at run time.
if [[ "$PLATFORM" == "macos" ]]; then
    if command -v install_name_tool >/dev/null 2>&1; then
        install_name_tool -id "@rpath/${DEFAULT_LIBJPEG_MAJOR}" "${LIBDIR}/${DEFAULT_LIBJPEG_REAL}"
        install_name_tool -id "@rpath/${DEFAULT_LIBTJ_MAJOR}" "${LIBDIR}/${DEFAULT_LIBTJ_REAL}"
    else
        echo "WARNING: install_name_tool not on PATH — installed cdylib's LC_ID_DYLIB will not match ${DEFAULT_LIBJPEG_MAJOR}. Consumers that resolve via install_name (the macOS default) will fail to load." >&2
    fi
elif [[ "$PLATFORM" == "linux" ]]; then
    if command -v patchelf >/dev/null 2>&1; then
        patchelf --set-soname "${DEFAULT_LIBJPEG_MAJOR}" "${LIBDIR}/${DEFAULT_LIBJPEG_REAL}"
        patchelf --set-soname "${DEFAULT_LIBTJ_MAJOR}" "${LIBDIR}/${DEFAULT_LIBTJ_REAL}"
    else
        echo "WARNING: patchelf not on PATH — installed cdylib's DT_SONAME will not match ${DEFAULT_LIBJPEG_MAJOR}. Downstream binaries linked against -ljpeg will record the build-time SONAME (typically libjpeg.so.8) in DT_NEEDED instead, and ldd will resolve them to the wrong file. Install patchelf (apt: patchelf / brew: patchelf) or rebuild the capi crate with CAPI_SONAME=${DEFAULT_LIBJPEG_MAJOR} before staging." >&2
    fi
fi

# Install upstream headers (verbatim — we are ABI-compatible with the
# v8 layout from references/libjpeg-turbo/src/jpeglib.h).
for header in jpeglib.h jerror.h jmorecfg.h turbojpeg.h; do
    install -m 0644 "$ROOT/references/libjpeg-turbo/src/$header" "$INCDIR/$header"
done

# jconfig.h: generate from the v8 defaults the build.rs / shim assume.
cat >"$INCDIR/jconfig.h" <<'EOF'
/* Generated by scripts/install_capi.sh — matches libjpeg-turbo-rs-capi
 * struct layout (JPEG_LIB_VERSION = 80, v8 ABI).
 *
 * See docs/ABI_COMPATIBILITY.md for the policy: consumers compiled
 * against this header link against our cdylib; consumers that need v6b
 * struct layout must use upstream libjpeg-turbo built without
 * WITH_JPEG7/WITH_JPEG8.
 */
#define JPEG_LIB_VERSION 80
#define LIBJPEG_TURBO_VERSION 3.1.0
#define LIBJPEG_TURBO_VERSION_NUMBER 3001000
#define C_ARITH_CODING_SUPPORTED 1
#define D_ARITH_CODING_SUPPORTED 1
#define MEM_SRCDST_SUPPORTED 1
#define WITH_SIMD 1
#ifndef BITS_IN_JSAMPLE
#define BITS_IN_JSAMPLE 8
#endif
EOF
chmod 0644 "$INCDIR/jconfig.h"

# Re-stage the build.rs-generated .pc files. We cannot read OUT_DIR
# directly (it's per-build), so regenerate from the same template here
# with the right ${prefix} substitution baked in.
cat >"$PKGCFGDIR/libjpeg.pc" <<EOF
prefix=${PREFIX}
exec_prefix=\${prefix}
libdir=\${prefix}/lib
includedir=\${prefix}/include

Name: libjpeg
Description: A SIMD-accelerated JPEG codec (libjpeg-turbo-rs shim)
Version: ${CDYLIB_VERSION}
Libs: -L\${libdir} -ljpeg
Cflags: -I\${includedir}
EOF

cat >"$PKGCFGDIR/libturbojpeg.pc" <<EOF
prefix=${PREFIX}
exec_prefix=\${prefix}
libdir=\${prefix}/lib
includedir=\${prefix}/include

Name: libturbojpeg
Description: A SIMD-accelerated JPEG codec (TurboJPEG API, libjpeg-turbo-rs shim)
Version: ${CDYLIB_VERSION}
Libs: -L\${libdir} -lturbojpeg
Cflags: -I\${includedir}
EOF

# Minimal CMake config so `find_package(JPEG)` resolves to our tree.
# Mirrors what FindJPEG.cmake produces but as a config-package so the
# user can pin to us via -DCMAKE_PREFIX_PATH=${PREFIX}.
cat >"$CMAKEDIR/JPEGConfig.cmake" <<EOF
# JPEG config package for libjpeg-turbo-rs-capi. Provides the variables
# and imported target FindJPEG.cmake exposes, so downstream
# CMake projects using \`find_package(JPEG)\` resolve here when
# \${CMAKE_PREFIX_PATH} points at this prefix.
set(JPEG_VERSION "${CDYLIB_VERSION}")
set(JPEG_INCLUDE_DIR "${PREFIX}/include")
set(JPEG_INCLUDE_DIRS "\${JPEG_INCLUDE_DIR}")
set(JPEG_LIBRARY "${PREFIX}/lib/${DEFAULT_LIBJPEG_DEV}")
set(JPEG_LIBRARIES "\${JPEG_LIBRARY}")
set(JPEG_FOUND TRUE)

if(NOT TARGET JPEG::JPEG)
    add_library(JPEG::JPEG UNKNOWN IMPORTED)
    set_target_properties(JPEG::JPEG PROPERTIES
        IMPORTED_LOCATION "\${JPEG_LIBRARY}"
        INTERFACE_INCLUDE_DIRECTORIES "\${JPEG_INCLUDE_DIR}"
    )
endif()
EOF

cat <<EOF
Installed libjpeg-turbo-rs-capi ${CDYLIB_VERSION} into ${DESTDIR}${PREFIX}:
  lib/${DEFAULT_LIBJPEG_REAL}    (cdylib)
  lib/${DEFAULT_LIBJPEG_MAJOR}, lib/${DEFAULT_LIBJPEG_DEV}    (symlinks)
  lib/${DEFAULT_LIBTJ_REAL}, lib/${DEFAULT_LIBTJ_MAJOR}, lib/${DEFAULT_LIBTJ_DEV}
  lib/pkgconfig/{libjpeg,libturbojpeg}.pc
  lib/cmake/JPEG/JPEGConfig.cmake
  include/{jpeglib,jerror,jmorecfg,jconfig,turbojpeg}.h
EOF
