#!/usr/bin/env bash
# install_capi.sh — stage `libjpeg-turbo-rs-capi`'s cdylib + headers +
# pkg-config + CMake config into a DESTDIR/PREFIX tree the way
# distro packagers expect.
#
# This is the P2-8 install path: it produces the layout that
# `pkg-config --libs libjpeg`, `find_package(JPEG)`, and consumers like
# Pillow / ImageMagick / libvips expect when our cdylib is dropped in
# place of upstream `libjpeg.so.8` / `libturbojpeg.so.0`. The default
# tracks the build.rs default (P4-3, 2026-05-17): v8 ABI / `libjpeg.so.8`
# / `@rpath/libjpeg.8.dylib`. v6b is an explicit opt-in.
#
# Usage:
#   scripts/install_capi.sh --destdir /tmp/install --prefix /usr
#
# Required env vs CLI flags (CLI wins):
#   --destdir DIR     Stage root (defaults to "")
#   --prefix DIR      Install prefix (defaults to "/usr/local"; on Windows
#                     "C:/libjpeg-turbo-rs64", beside upstream's
#                     "c:/libjpeg-turbo64" convention). With --destdir, a
#                     drive-lettered prefix is staged below DESTDIR without
#                     its drive.
#   --soname NAME     libjpeg "major" SONAME on Linux (default
#                     "libjpeg.so.8"; pass "libjpeg.so.62" to opt into
#                     the v6b SONAME — docs/ABI_COMPATIBILITY.md flags
#                     v6b as the documented-risk path for v8-layout
#                     consumers). On macOS, accepts the compat dylib name
#                     (default "libjpeg.8.dylib"). The real cdylib
#                     filename is derived as
#                     "${soname}.${version}" (Linux) or
#                     "${soname%.dylib}.${version}.dylib" (macOS).
#                     On Windows it is the DLL file name (default
#                     "jpeg8.dll", upstream's WITH_JPEG8 name; "jpeg62.dll"
#                     is the v6b opt-in) — there is no SONAME, the file name
#                     is what a consumer's import table records.
#   --soname-tj NAME  libturbojpeg "major" SONAME (default
#                     "libturbojpeg.so.0" / "libturbojpeg.0.dylib" /
#                     "turbojpeg.dll").
#   --build           Force a cdylib build. Without it, a missing cdylib is
#                     still built automatically.
#   CAPI_TARGET_DIR   Exact target-qualified Cargo release directory containing
#                     the cdylib. Relative paths use `$ROOT`. With `--build`,
#                     it must end in `/<target-triple>/release` so Cargo can
#                     derive its target root. Defaults below CARGO_TARGET_DIR
#                     (or `$ROOT/target`) using CAPI_BUILD_TARGET.
#   CAPI_BUILD_TARGET Cargo target passed explicitly to nested builds. Defaults
#                     to CARGO_BUILD_TARGET when set, otherwise Cargo's host.
#
# Layout produced under ${DESTDIR}${PREFIX} (defaults — v8):
#   lib/libjpeg.so.8.X.Y           actual cdylib
#   lib/libjpeg.so.8               symlink → .X.Y
#   lib/libjpeg.so                 symlink → libjpeg.so.8
#   lib/libturbojpeg.so.0.X.Y      hardlink/copy of the cdylib
#   lib/libturbojpeg.so.0          symlink → .X.Y
#   lib/libturbojpeg.so            symlink → libturbojpeg.so.0
#   lib/pkgconfig/libjpeg.pc       generated by build.rs (re-staged here)
#   lib/pkgconfig/libturbojpeg.pc  generated by build.rs (re-staged here)
#   lib/cmake/JPEG/JPEGConfig.cmake  CMake `find_package(JPEG)` shim
#   share/doc/libjpeg-turbo-rs-capi/LICENSE-{MIT,APACHE}
#   include/jpeglib.h              from references/libjpeg-turbo/src/
#   include/jerror.h               from references/libjpeg-turbo/src/
#   include/jmorecfg.h             from references/libjpeg-turbo/src/
#   include/jconfig.h              generated (matches build.rs's v8 defaults)
#   include/turbojpeg.h            from references/libjpeg-turbo/src/
#
# On Windows (x86_64-pc-windows-msvc only, run from Git for Windows' bash),
# the library part is upstream's MSVC layout instead — P4-131:
#   bin/jpeg8.dll                  the DLL, under the name consumers load
#   lib/jpeg.lib                   import library, bound to jpeg8.dll
#   bin/turbojpeg.dll              the same DLL under the TurboJPEG name
#   lib/turbojpeg.lib              import library, bound to turbojpeg.dll
# with the same pkgconfig/, cmake/, share/doc/ and include/ entries.

set -euo pipefail

# Path shapes. Under Git for Windows' bash this script receives Windows paths
# (`C:\...`, from `cargo test` or a PowerShell caller) and must hand POSIX
# ones to coreutils and Windows ones to cargo and the MSVC tools; `cygpath`
# exists exactly there. Everywhere else both are the identity.
posix_path() {
    if command -v cygpath >/dev/null 2>&1; then cygpath -u "$1"; else printf '%s\n' "$1"; fi
}
native_path() {
    if command -v cygpath >/dev/null 2>&1; then cygpath -m "$1"; else printf '%s\n' "$1"; fi
}

DESTDIR=""
PREFIX=""
SONAME=""
SONAME_TJ=""
DO_BUILD=0
ROOT="$(cd "$(dirname "$(posix_path "$0")")/.." && pwd)"
CARGO_BIN="${CARGO:-cargo}"

resolve_build_target() {
    if [[ -n "${CAPI_BUILD_TARGET:-}" ]]; then
        printf '%s\n' "$CAPI_BUILD_TARGET"
    elif [[ -n "${CARGO_BUILD_TARGET:-}" ]]; then
        printf '%s\n' "$CARGO_BUILD_TARGET"
    else
        "$CARGO_BIN" -vV | tr -d '\r' | sed -n 's/^host: //p'
    fi
}

target_component() {
    local target="$1"
    basename "${target%.json}"
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --destdir)    DESTDIR="$2"; shift 2 ;;
        --prefix)     PREFIX="$2"; shift 2 ;;
        --soname)     SONAME="$2"; shift 2 ;;
        --soname-tj)  SONAME_TJ="$2"; shift 2 ;;
        --build)      DO_BUILD=1; shift ;;
        --root)       ROOT="$2"; shift 2 ;;
        -h|--help)
            sed -n '2,/^set -euo/p' "$0" | sed 's/^# *//'
            exit 0
            ;;
        *) echo "unknown arg: $1" >&2; exit 1 ;;
    esac
done

if [[ -n "$DESTDIR" ]]; then DESTDIR="$(posix_path "$DESTDIR")"; fi
ROOT="$(posix_path "$ROOT")"
if [[ -n "${CAPI_TARGET_DIR:-}" ]]; then CAPI_TARGET_DIR="$(posix_path "$CAPI_TARGET_DIR")"; fi
CARGO_BIN="$(posix_path "$CARGO_BIN")"

OS_NAME="$(uname -s)"
case "$OS_NAME" in
    Linux*)  PLATFORM=linux ;;
    Darwin*) PLATFORM=macos ;;
    # Git for Windows' bash reports MINGW64_NT-<version>; MSYS2 and Cygwin
    # shells can run the same script.
    MINGW*|MSYS*|CYGWIN*) PLATFORM=windows ;;
    *) echo "unsupported platform: $OS_NAME" >&2; exit 1 ;;
esac

if [[ "$PLATFORM" == "windows" ]] && ! command -v cygpath >/dev/null 2>&1; then
    # Without it every path helper above is the identity and `C:\...` gets
    # `/lib` appended — directories in surprising places rather than a failure.
    echo "ERROR: cygpath not found; run this from Git for Windows' bash (C:\\Program Files\\Git\\bin\\bash.exe)." >&2
    exit 1
fi

if [[ -z "$PREFIX" ]]; then
    case "$PLATFORM" in
        windows) PREFIX="C:/libjpeg-turbo-rs64" ;;
        *)       PREFIX="/usr/local" ;;
    esac
fi
# A PowerShell caller spells the prefix `C:\libjpeg-turbo-rs64`; the `.pc`
# and CMake files want forward slashes (CMake reads `\l` as an escape), and
# so does the DESTDIR arithmetic below.
PREFIX="${PREFIX//\\//}"
if [[ "$PLATFORM" == "windows" && ! "$PREFIX" =~ ^([A-Za-z]:)?/ ]]; then
    echo "prefix must be absolute (C:/... or /...): ${PREFIX}" >&2
    exit 1
fi

BUILD_TARGET=""
case "${CAPI_TARGET_DIR:-}" in
    "")
        BUILD_TARGET="$(resolve_build_target)"
        [[ -n "$BUILD_TARGET" ]] || { echo "could not resolve Cargo build target" >&2; exit 1; }
        case "${CARGO_TARGET_DIR:-}" in
            "")  CARGO_TARGET_ROOT="$ROOT/target" ;;
            /*)  CARGO_TARGET_ROOT="$CARGO_TARGET_DIR" ;;
            *)   CARGO_TARGET_ROOT="$ROOT/$CARGO_TARGET_DIR" ;;
        esac
        RELEASE_DIR="$CARGO_TARGET_ROOT/$(target_component "$BUILD_TARGET")/release"
        ;;
    /*)  RELEASE_DIR="$CAPI_TARGET_DIR" ;;
    *)   RELEASE_DIR="$ROOT/$CAPI_TARGET_DIR" ;;
esac

# Resolve cdylib path + version from Cargo.toml.
CDYLIB_VERSION="$(grep '^version' "$ROOT/crates/libjpeg-turbo-rs-capi/Cargo.toml" | head -1 | sed 's/.*"\(.*\)".*/\1/')"
case "$PLATFORM" in
    linux)
        CDYLIB_FILE="$RELEASE_DIR/liblibjpeg_turbo_rs_capi.so"
        # P4-3 (2026-05-17): default flipped from libjpeg.so.62 → libjpeg.so.8
        # to match the build.rs SONAME default and the v8 struct layout.
        DEFAULT_LIBJPEG_MAJOR="libjpeg.so.8"
        DEFAULT_LIBJPEG_DEV="libjpeg.so"
        DEFAULT_LIBTJ_MAJOR="libturbojpeg.so.0"
        DEFAULT_LIBTJ_DEV="libturbojpeg.so"
        ;;
    macos)
        CDYLIB_FILE="$RELEASE_DIR/liblibjpeg_turbo_rs_capi.dylib"
        # P4-3 (2026-05-17): default flipped from libjpeg.62.dylib → libjpeg.8.dylib
        # to match the build.rs install_name default and the v8 struct layout.
        DEFAULT_LIBJPEG_MAJOR="libjpeg.8.dylib"
        DEFAULT_LIBJPEG_DEV="libjpeg.dylib"
        DEFAULT_LIBTJ_MAJOR="libturbojpeg.0.dylib"
        DEFAULT_LIBTJ_DEV="libturbojpeg.dylib"
        ;;
    windows)
        CDYLIB_FILE="$RELEASE_DIR/libjpeg_turbo_rs_capi.dll"
        # Upstream's MSVC names (sharedlib/CMakeLists.txt, RUNTIME_OUTPUT_NAME
        # jpeg${SO_MAJOR_VERSION}): the DLL carries the ABI major, the import
        # library does not. A consumer built against upstream's v8 build has
        # `jpeg8.dll` in its import table, so the name is the identity.
        DEFAULT_LIBJPEG_MAJOR="jpeg8.dll"
        DEFAULT_LIBJPEG_DEV="jpeg.lib"
        DEFAULT_LIBTJ_MAJOR="turbojpeg.dll"
        DEFAULT_LIBTJ_DEV="turbojpeg.lib"
        # One target, one layout. MinGW names its DLLs `libjpeg-8.dll` and
        # links through `libjpeg.dll.a`, and `-ljpeg` in the staged `.pc`
        # means a different file under each toolchain; the bundle P4-131
        # ships is the MSVC one, so refuse to stage another under its name.
        BUILD_TARGET="${BUILD_TARGET:-$(resolve_build_target)}"
        if [[ "$BUILD_TARGET" != x86_64-*-windows-msvc ]]; then
            echo "unsupported Windows target for install staging: ${BUILD_TARGET} (P4-131 stages the x86_64-pc-windows-msvc layout only)" >&2
            exit 1
        fi
        ;;
esac

# Honor --soname / --soname-tj overrides.
LIBJPEG_MAJOR="${SONAME:-$DEFAULT_LIBJPEG_MAJOR}"
LIBTJ_MAJOR="${SONAME_TJ:-$DEFAULT_LIBTJ_MAJOR}"

# Derive the real (versioned) cdylib filename from the major SONAME.
# Linux: append .${VERSION} (e.g. libjpeg.so.8 → libjpeg.so.8.X.Y).
# macOS: insert ${VERSION} before the .dylib suffix (e.g. libjpeg.8.dylib
#        → libjpeg.8.X.Y.dylib).
# Derive the bare dev-link filename: drop everything from the SONAME
# digit onward (Linux) or the major digit before .dylib (macOS) so
# packagers passing a non-default --soname still get a sensible
# `libjpeg.{so,dylib}` symlink at the top of the chain.
case "$PLATFORM" in
    linux)
        LIBJPEG_REAL="${LIBJPEG_MAJOR}.${CDYLIB_VERSION}"
        LIBTJ_REAL="${LIBTJ_MAJOR}.${CDYLIB_VERSION}"
        # Strip everything after `.so` to get the dev link.
        LIBJPEG_DEV="${LIBJPEG_MAJOR%%.so*}.so"
        LIBTJ_DEV="${LIBTJ_MAJOR%%.so*}.so"
        ;;
    macos)
        LIBJPEG_REAL="${LIBJPEG_MAJOR%.dylib}.${CDYLIB_VERSION}.dylib"
        LIBTJ_REAL="${LIBTJ_MAJOR%.dylib}.${CDYLIB_VERSION}.dylib"
        # Strip the version digits before .dylib to get the dev link.
        # `libjpeg.62.dylib` → `libjpeg.dylib`.
        LIBJPEG_DEV="$(echo "$LIBJPEG_MAJOR" | sed 's/\.[0-9][0-9]*\.dylib$/.dylib/')"
        LIBTJ_DEV="$(echo "$LIBTJ_MAJOR" | sed 's/\.[0-9][0-9]*\.dylib$/.dylib/')"
        ;;
    windows)
        # No versioned file and no chain: the DLL is installed under the
        # major name itself, and the "dev" entry is the import library, whose
        # name upstream keeps constant across ABI majors (`jpeg.lib` for both
        # jpeg62.dll and jpeg8.dll).
        LIBJPEG_REAL="$LIBJPEG_MAJOR"
        LIBTJ_REAL="$LIBTJ_MAJOR"
        LIBJPEG_DEV="$DEFAULT_LIBJPEG_DEV"
        LIBTJ_DEV="$DEFAULT_LIBTJ_DEV"
        ;;
esac

# Replace the now-unused defaults with the resolved names so the
# install/symlink steps below pick them up.
DEFAULT_LIBJPEG_REAL="$LIBJPEG_REAL"
DEFAULT_LIBJPEG_MAJOR="$LIBJPEG_MAJOR"
DEFAULT_LIBJPEG_DEV="$LIBJPEG_DEV"
DEFAULT_LIBTJ_REAL="$LIBTJ_REAL"
DEFAULT_LIBTJ_MAJOR="$LIBTJ_MAJOR"
DEFAULT_LIBTJ_DEV="$LIBTJ_DEV"

if [[ "$DO_BUILD" -eq 1 || ! -f "$CDYLIB_FILE" ]]; then
    BUILD_TARGET="${BUILD_TARGET:-$(resolve_build_target)}"
    [[ -n "$BUILD_TARGET" ]] || { echo "could not resolve Cargo build target" >&2; exit 1; }
    TARGET_COMPONENT="$(target_component "$BUILD_TARGET")"
    if [[ "$(basename "$RELEASE_DIR")" != "release" ||
          "$(basename "$(dirname "$RELEASE_DIR")")" != "$TARGET_COMPONENT" ]]; then
        echo "CAPI_TARGET_DIR must end in /${TARGET_COMPONENT}/release when building: $RELEASE_DIR" >&2
        exit 1
    fi
    CARGO_TARGET_ROOT="$(dirname "$(dirname "$RELEASE_DIR")")"
    # cargo is a native program: on Windows it needs `C:/...`, not `/c/...`.
    (cd "$ROOT" && CARGO_TARGET_DIR="$(native_path "$CARGO_TARGET_ROOT")" \
        "$CARGO_BIN" build -p libjpeg-turbo-rs-capi --release --target "$BUILD_TARGET")
fi
[[ -f "$CDYLIB_FILE" ]] || { echo "cdylib not found: $CDYLIB_FILE" >&2; exit 1; }

# ---------------------------------------------------------------------------
# P4-81: GNU symbol versions on the shipped ELF library.
#
# The cdylib cargo produces cannot carry them. rustc passes its own version
# script for every cdylib -- an *anonymous* tag, `{ global: ...; local: *; };`
# -- and GNU ld refuses to combine an anonymous version tag with named ones,
# so adding `LIBJPEG_8.0` as a second script fails the link outright with
# `anonymous version tag cannot be combined with other version tags`. Verified
# against binutils 2.47 across every script surface, including `.symver`, which
# fails differently (`version node not found`) because it attaches a symbol to
# a node without defining one. rustc exposes no knob to suppress its script.
#
# The one configuration that works is a single named script carrying `local: *`
# itself -- so whoever owns the link owns the versioning. Here we do: relink the
# shipped library from the staticlib the crate already builds.
#
# Policy mirrors the test-suite rule (P4-116): a missing prerequisite is
# environmental and degrades with a loud warning, but a relink we *attempt* and
# that fails is a defect and stops the install rather than silently shipping an
# unversioned library that callers believe is versioned.
# ---------------------------------------------------------------------------
JPEG_LIB_SOURCE="$CDYLIB_FILE"
if [[ "$PLATFORM" == "linux" && "${CAPI_SKIP_SYMBOL_VERSIONS:-0}" != "1" ]]; then
    if [[ "$LIBJPEG_MAJOR" != libjpeg.so.8* ]]; then
        echo "note: SONAME '${LIBJPEG_MAJOR}' is not the v8 identity; shipping without symbol versions (P4-81)" >&2
    else
        # The map lives under `<profile>/build/<pkg>-<hash>/out/`. Callers may
        # point CAPI_TARGET_DIR at `<profile>/deps` (that is where the test
        # harness finds the cdylib), so `build/` can be one level up. Prefer the
        # newest when several build-script hashes are present.
        VERSION_MAP=""
        for _dir in "$RELEASE_DIR" "$(dirname "$RELEASE_DIR")"; do
            [[ -d "$_dir/build" ]] || continue
            VERSION_MAP="$(find "$_dir/build" -type f -name libjpeg.map -exec ls -t {} + 2>/dev/null | head -1)"
            [[ -n "$VERSION_MAP" ]] && break
        done
        STATIC_LIB=""
        for _dir in "$RELEASE_DIR" "$(dirname "$RELEASE_DIR")"; do
            if [[ -f "$_dir/liblibjpeg_turbo_rs_capi.a" ]]; then
                STATIC_LIB="$_dir/liblibjpeg_turbo_rs_capi.a"
                break
            fi
        done
        CC_BIN="${CC:-cc}"
        if [[ -z "$VERSION_MAP" || -z "$STATIC_LIB" ]] || ! command -v "$CC_BIN" >/dev/null 2>&1; then
            echo "warning: cannot add GNU symbol versions (map='${VERSION_MAP:-missing}', staticlib='${STATIC_LIB:-missing}', cc='${CC_BIN}')." >&2
            echo "         Shipping the unversioned cdylib; prebuilt consumers will see 'no version information available' (P4-81)." >&2
        else
            # Per-invocation output. A fixed name here is shared state: two
            # concurrent installs against one `RELEASE_DIR` — which is what
            # `cargo test` does the moment a second suite stages the prefix,
            # since libtest runs a binary's tests on parallel threads and cargo
            # runs the binaries in parallel too — would have `ld` truncate each
            # other's output, and the loser stages a short library that every
            # existence check still passes. The `.versioned.*` name keeps the
            # artifact recognisable; the trap keeps it from accumulating in
            # `deps/` the way the fixed name did.
            VERSIONED_LIB="$(mktemp "${RELEASE_DIR}/${LIBJPEG_MAJOR}.${CDYLIB_VERSION}.versioned.XXXXXX")"
            trap 'rm -f "$VERSIONED_LIB"' EXIT INT TERM
            # --whole-archive: nothing references the `#[no_mangle]` exports, so
            #   without it the linker drops the entire archive.
            # --allow-multiple-definition: Rust staticlibs bundle compiler_builtins
            #   symbols that also arrive from libgcc.
            if ! "$CC_BIN" -shared -o "$VERSIONED_LIB" \
                    -Wl,--whole-archive "$STATIC_LIB" -Wl,--no-whole-archive \
                    -Wl,--version-script,"$VERSION_MAP" \
                    -Wl,-soname,"$LIBJPEG_MAJOR" \
                    -Wl,--allow-multiple-definition \
                    -lpthread -ldl -lm; then
                echo "ERROR: relinking ${LIBJPEG_MAJOR} with ${VERSION_MAP} failed." >&2
                echo "       Set CAPI_SKIP_SYMBOL_VERSIONS=1 to install the unversioned cdylib instead." >&2
                exit 1
            fi
            JPEG_LIB_SOURCE="$VERSIONED_LIB"
            echo "P4-81: relinked ${LIBJPEG_MAJOR} from the staticlib with GNU symbol versions"
        fi
    fi
fi

# ---------------------------------------------------------------------------
# Windows (P4-131): upstream's MSVC layout — `bin/jpeg8.dll` with the import
# library `lib/jpeg.lib`, `bin/turbojpeg.dll` with `lib/turbojpeg.lib`.
#
# There is no SONAME chain. A consumer's import table records the DLL's file
# name, so the name *is* the identity, and `jpeg8.dll` is what an executable
# built against upstream's v8 (WITH_JPEG8) MSVC build asks the loader for.
# cargo emits `libjpeg_turbo_rs_capi.dll`, and copying it under the upstream
# name is only half of the job: the import library cargo writes beside it
# binds every symbol to *that* file name, so a consumer linked through it
# would load `libjpeg_turbo_rs_capi.dll` and fail on a host that has only the
# bundle. The import library is therefore regenerated from the DLL's own
# export table under the shipped name — `dumpbin` lists what the DLL exports,
# `lib /DEF` binds those names to `jpeg8.dll` — which is the Windows
# counterpart of the `patchelf --set-soname` below. The DLL's bytes are
# cargo's, unchanged; only its file name and the import library differ. (Its
# export directory still records the original name; the loader never reads
# it.) Both tools live beside the `link.exe` rustc needed to build the DLL,
# so a host that built it has them; they are found the way rustc finds the
# linker when no developer shell put them on PATH.
#
# `-Brepro` makes the import library reproducible: without it lib.exe stamps
# the current time into every archive member, and the release bundle would
# differ from a second staging run of the same DLL — which is exactly the
# comparison `release_bundle.rs` makes to hold the one-staging-path rule.
# ---------------------------------------------------------------------------

# The MSVC tool named by $1: from PATH (a developer shell) or the newest
# Visual Studio toolset that vswhere reports (rustc's own fallback). A
# candidate counts only if it identifies itself as Microsoft's — a stub of
# the same name on PATH (a package-manager shim, Strawberry Perl's bin) would
# otherwise win and fail later with a message about the wrong program.
# Prints nothing and fails when there is none.
msvc_tool() {
    local tool="$1" vswhere install_dir candidate banner
    local -a candidates=()
    if command -v "$tool" >/dev/null 2>&1; then
        candidates+=("$(command -v "$tool")")
    fi
    for vswhere in "/c/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe" \
                   "$(command -v vswhere.exe 2>/dev/null || true)"; do
        [[ -n "$vswhere" && -f "$vswhere" ]] || continue
        install_dir="$("$vswhere" -latest -products '*' \
            -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 \
            -property installationPath 2>/dev/null | tr -d '\r' | awk 'NR == 1')"
        [[ -n "$install_dir" ]] || continue
        # The toolset layout is fixed; a glob costs one directory listing
        # where `find` would stat the whole toolset tree on every call.
        # Newest toolset first.
        while IFS= read -r candidate; do
            [[ -f "$candidate" ]] && candidates+=("$candidate")
        done < <(printf '%s\n' "$(posix_path "$install_dir")"/VC/Tools/MSVC/*/bin/Hostx64/x64/"$tool" | sort -rV)
    done
    for candidate in ${candidates[@]+"${candidates[@]}"}; do
        banner="$(MSYS_NO_PATHCONV=1 MSYS2_ARG_CONV_EXCL='*' "$candidate" 2>&1 | head -3 || true)"
        case "$banner" in
            *Microsoft*) printf '%s\n' "$candidate"; return 0 ;;
        esac
    done
    return 1
}

# Writes a `.def` naming every export of $1 (the DLL) under the DLL name $2,
# and an import library bound to that name at $3.
write_import_library() {
    local dll="$1" dll_name="$2" import_library="$3"
    local work exports def count
    work="$(mktemp -d)"
    # shellcheck disable=SC2064
    trap "rm -rf '$work'" RETURN
    exports="$work/exports.txt"
    def="$work/${dll_name%.dll}.def"
    # `-` rather than `/` for the options, and native paths for the files:
    # the MSYS runtime rewrites arguments that look like POSIX paths before
    # a native program sees them, and `/EXPORTS` looks like one. The env
    # vars switch that rewriting off for the call as well. The tools' own
    # directory goes on PATH for the call: they load `mspdbcore.dll` and
    # friends from beside themselves, which a developer shell arranges and a
    # plain invocation by absolute path may not.
    if ! MSYS_NO_PATHCONV=1 MSYS2_ARG_CONV_EXCL='*' PATH="$(dirname "$DUMPBIN"):$PATH" \
            "$DUMPBIN" -NOLOGO -EXPORTS "$(native_path "$dll")" > "$work/dumpbin.txt" 2>&1; then
        echo "ERROR: dumpbin could not read ${dll}:" >&2
        cat "$work/dumpbin.txt" >&2
        exit 1
    fi
    # The export table rows: `ordinal hint RVA name`, followed by
    # `= <symbol>` when dumpbin can name the code behind the export — it does
    # for this DLL, and identical-code folding makes several exports share
    # one symbol there (`jpeg_c_get_bool_param = jpeg_c_bool_param_supported`),
    # so the fourth field is the export name and the rest is ignored. Every
    # export of this crate is a `#[no_mangle] extern "C" fn`; a
    # `#[no_mangle] static` would need the `DATA` keyword here, which the
    # listing does not reveal, so one must not be added to the crate without
    # extending this writer.
    tr -d '\r' < "$work/dumpbin.txt" \
        | awk 'NF >= 4 && $1 ~ /^[0-9]+$/ && $3 ~ /^[0-9A-Fa-f]+$/ { print $4 }' \
        > "$exports"
    count="$(wc -l < "$exports" | tr -d ' ')"
    # Both API surfaces and a plausible count: a parse that dropped most rows
    # would still produce a valid import library that links nothing.
    if ! grep -qx 'jpeg_std_error' "$exports" || ! grep -qx 'tj3Init' "$exports" || [[ "$count" -lt 100 ]]; then
        echo "ERROR: parsed only ${count} exports from ${dll}; expected the full jpeg_*/tj* surface. dumpbin said:" >&2
        head -40 "$work/dumpbin.txt" >&2
        exit 1
    fi
    {
        echo "LIBRARY ${dll_name}"
        echo "EXPORTS"
        sed 's/^/    /' "$exports"
    } > "$def"
    if ! MSYS_NO_PATHCONV=1 MSYS2_ARG_CONV_EXCL='*' PATH="$(dirname "$LIB_TOOL"):$PATH" \
            "$LIB_TOOL" -NOLOGO -MACHINE:X64 -Brepro \
            -DEF:"$(native_path "$def")" -OUT:"$(native_path "$work/out.lib")"; then
        echo "ERROR: lib.exe could not build the import library for ${dll_name} from ${def}." >&2
        exit 1
    fi
    install -m 0644 "$work/out.lib" "$import_library"
}

# Resolve the Windows tools before anything is created below DESTDIR, so a
# host without them is told so and left clean.
if [[ "$PLATFORM" == "windows" ]]; then
    DUMPBIN="$(msvc_tool dumpbin.exe)" || {
        echo "ERROR: dumpbin.exe not found. Run from a Visual Studio developer shell, or install the VC++ build tools rustc needs for x86_64-pc-windows-msvc." >&2
        exit 1
    }
    LIB_TOOL="$(msvc_tool lib.exe)" || {
        echo "ERROR: lib.exe not found. Run from a Visual Studio developer shell, or install the VC++ build tools rustc needs for x86_64-pc-windows-msvc." >&2
        exit 1
    }
fi

# Stage roots. A drive-lettered prefix (`C:/libjpeg-turbo-rs64`) cannot be
# appended to DESTDIR as-is; below DESTDIR it loses its drive, the way CMake's
# DESTDIR handling does on Windows.
if [[ -n "$DESTDIR" && "$PREFIX" =~ ^[A-Za-z]: ]]; then
    STAGE_ROOT="${DESTDIR}${PREFIX:2}"
else
    STAGE_ROOT="${DESTDIR}${PREFIX}"
fi
LIBDIR="${STAGE_ROOT}/lib"
BINDIR="${STAGE_ROOT}/bin"
INCDIR="${STAGE_ROOT}/include"
PKGCFGDIR="${LIBDIR}/pkgconfig"
CMAKEDIR="${LIBDIR}/cmake/JPEG"
DOCDIR="${STAGE_ROOT}/share/doc/libjpeg-turbo-rs-capi"
mkdir -p "$LIBDIR" "$INCDIR" "$PKGCFGDIR" "$CMAKEDIR" "$DOCDIR"

if [[ "$PLATFORM" == "windows" ]]; then
    mkdir -p "$BINDIR"
    install -m 0755 "$JPEG_LIB_SOURCE" "${BINDIR}/${DEFAULT_LIBJPEG_REAL}"
    write_import_library "$JPEG_LIB_SOURCE" "$DEFAULT_LIBJPEG_MAJOR" "${LIBDIR}/${DEFAULT_LIBJPEG_DEV}"
    # libturbojpeg is the same binary under the TurboJPEG name, as below.
    install -m 0755 "$JPEG_LIB_SOURCE" "${BINDIR}/${DEFAULT_LIBTJ_REAL}"
    write_import_library "$JPEG_LIB_SOURCE" "$DEFAULT_LIBTJ_MAJOR" "${LIBDIR}/${DEFAULT_LIBTJ_DEV}"
else
    # Install cdylib + symlink chains.
    install -m 0755 "$JPEG_LIB_SOURCE" "${LIBDIR}/${DEFAULT_LIBJPEG_REAL}"
    ln -sf "$DEFAULT_LIBJPEG_REAL" "${LIBDIR}/${DEFAULT_LIBJPEG_MAJOR}"
    ln -sf "$DEFAULT_LIBJPEG_MAJOR" "${LIBDIR}/${DEFAULT_LIBJPEG_DEV}"
    # libturbojpeg shares the same binary (we export both APIs).
    # Same binary: our map has no catch-all node, so the tj* surface stays
    # unversioned exactly as before (P4-81).
    install -m 0755 "$JPEG_LIB_SOURCE" "${LIBDIR}/${DEFAULT_LIBTJ_REAL}"
    ln -sf "$DEFAULT_LIBTJ_REAL" "${LIBDIR}/${DEFAULT_LIBTJ_MAJOR}"
    ln -sf "$DEFAULT_LIBTJ_MAJOR" "${LIBDIR}/${DEFAULT_LIBTJ_DEV}"
fi

# Rewrite each installed cdylib's identity (macOS install_name /
# Linux DT_SONAME) so it matches the SONAME the script was told
# about. Without this, `--soname libjpeg.so.62` (or its macOS twin
# `libjpeg.62.dylib`) would stage a v6b symlink chain but leave the
# cdylib advertising the build-time identity (typically `libjpeg.so.8`
# / `@rpath/libjpeg.8.dylib`), and the dynamic linker would refuse to
# load it under the v6b name — or, on Linux, a downstream linked
# against `-ljpeg` would record `libjpeg.so.8` in its DT_NEEDED
# instead of `libjpeg.so.62`, so `ldd` would resolve to the wrong
# file at run time.
if [[ "$PLATFORM" == "macos" ]]; then
    if command -v install_name_tool >/dev/null 2>&1; then
        install_name_tool -id "@rpath/${DEFAULT_LIBJPEG_MAJOR}" "${LIBDIR}/${DEFAULT_LIBJPEG_REAL}"
        install_name_tool -id "@rpath/${DEFAULT_LIBTJ_MAJOR}" "${LIBDIR}/${DEFAULT_LIBTJ_REAL}"
    else
        echo "WARNING: install_name_tool not on PATH — installed cdylib's LC_ID_DYLIB will not match ${DEFAULT_LIBJPEG_MAJOR}. Consumers that resolve via install_name (the macOS default) will fail to load." >&2
    fi
elif [[ "$PLATFORM" == "linux" ]]; then
    if command -v patchelf >/dev/null 2>&1; then
        patchelf --set-soname "${DEFAULT_LIBJPEG_MAJOR}" "${LIBDIR}/${DEFAULT_LIBJPEG_REAL}"
        patchelf --set-soname "${DEFAULT_LIBTJ_MAJOR}" "${LIBDIR}/${DEFAULT_LIBTJ_REAL}"
    else
        echo "WARNING: patchelf not on PATH — installed cdylib's DT_SONAME will not match ${DEFAULT_LIBJPEG_MAJOR}. Downstream binaries linked against -ljpeg will record the build-time SONAME (typically libjpeg.so.8) in DT_NEEDED instead, and ldd will resolve them to the wrong file. Install patchelf (apt: patchelf / brew: patchelf) or rebuild the capi crate with CAPI_SONAME=${DEFAULT_LIBJPEG_MAJOR} before staging." >&2
    fi
fi

# Both license texts. MIT and Apache-2.0 each require the notice to travel
# with a *binary* redistribution, and since P4-131 this staged tree is
# redistributed as a downloadable archive rather than only installed on the
# machine that built it. `share/doc/<pkg>/` is where upstream libjpeg-turbo
# puts its own, so a packager finds them where they expect.
for license in LICENSE-MIT LICENSE-APACHE; do
    install -m 0644 "$ROOT/$license" "$DOCDIR/$license"
done

# Install upstream headers (verbatim — we are ABI-compatible with the
# v8 layout from references/libjpeg-turbo/src/jpeglib.h).
for header in jpeglib.h jerror.h jmorecfg.h turbojpeg.h; do
    install -m 0644 "$ROOT/references/libjpeg-turbo/src/$header" "$INCDIR/$header"
done

# jconfig.h: generate from the v8 defaults the build.rs / shim assume.
cat >"$INCDIR/jconfig.h" <<'EOF'
/* Generated by scripts/install_capi.sh — matches libjpeg-turbo-rs-capi
 * struct layout (JPEG_LIB_VERSION = 80, v8 ABI).
 *
 * See docs/ABI_COMPATIBILITY.md for the policy: consumers compiled
 * against this header link against our cdylib; consumers that need v6b
 * struct layout must use upstream libjpeg-turbo built without
 * WITH_JPEG7/WITH_JPEG8.
 */
#define JPEG_LIB_VERSION 80
#define LIBJPEG_TURBO_VERSION 3.1.0
#define LIBJPEG_TURBO_VERSION_NUMBER 3001000
#define C_ARITH_CODING_SUPPORTED 1
#define D_ARITH_CODING_SUPPORTED 1
#define MEM_SRCDST_SUPPORTED 1
#define WITH_SIMD 1
#ifndef BITS_IN_JSAMPLE
#define BITS_IN_JSAMPLE 8
#endif
EOF
chmod 0644 "$INCDIR/jconfig.h"

# Re-stage the build.rs-generated .pc files. We cannot read OUT_DIR
# directly (it's per-build), so regenerate from the same template here
# with the right ${prefix} substitution baked in.
cat >"$PKGCFGDIR/libjpeg.pc" <<EOF
prefix=${PREFIX}
exec_prefix=\${prefix}
libdir=\${prefix}/lib
includedir=\${prefix}/include

Name: libjpeg
Description: A SIMD-accelerated JPEG codec (libjpeg-turbo-rs shim)
Version: ${CDYLIB_VERSION}
Libs: -L\${libdir} -ljpeg
Cflags: -I\${includedir}
EOF

cat >"$PKGCFGDIR/libturbojpeg.pc" <<EOF
prefix=${PREFIX}
exec_prefix=\${prefix}
libdir=\${prefix}/lib
includedir=\${prefix}/include

Name: libturbojpeg
Description: A SIMD-accelerated JPEG codec (TurboJPEG API, libjpeg-turbo-rs shim)
Version: ${CDYLIB_VERSION}
Libs: -L\${libdir} -lturbojpeg
Cflags: -I\${includedir}
EOF

# Minimal CMake config so `find_package(JPEG)` resolves to our tree.
# Mirrors what FindJPEG.cmake produces but as a config-package so the
# user can pin to us via -DCMAKE_PREFIX_PATH=${PREFIX}.
cat >"$CMAKEDIR/JPEGConfig.cmake" <<EOF
# JPEG config package for libjpeg-turbo-rs-capi. Provides the variables
# and imported target FindJPEG.cmake exposes, so downstream
# CMake projects using \`find_package(JPEG)\` resolve here when
# \${CMAKE_PREFIX_PATH} points at this prefix.
set(JPEG_VERSION "${CDYLIB_VERSION}")
set(JPEG_INCLUDE_DIR "${PREFIX}/include")
set(JPEG_INCLUDE_DIRS "\${JPEG_INCLUDE_DIR}")
set(JPEG_LIBRARY "${PREFIX}/lib/${DEFAULT_LIBJPEG_DEV}")
set(JPEG_LIBRARIES "\${JPEG_LIBRARY}")
set(JPEG_FOUND TRUE)

if(NOT TARGET JPEG::JPEG)
    add_library(JPEG::JPEG UNKNOWN IMPORTED)
    set_target_properties(JPEG::JPEG PROPERTIES
        IMPORTED_LOCATION "\${JPEG_LIBRARY}"
        INTERFACE_INCLUDE_DIRECTORIES "\${JPEG_INCLUDE_DIR}"
    )
endif()
EOF

if [[ "$PLATFORM" == "windows" ]]; then
    LIBRARY_SUMMARY="  bin/${DEFAULT_LIBJPEG_REAL}, bin/${DEFAULT_LIBTJ_REAL}    (DLLs)
  lib/${DEFAULT_LIBJPEG_DEV}, lib/${DEFAULT_LIBTJ_DEV}    (import libraries)"
else
    LIBRARY_SUMMARY="  lib/${DEFAULT_LIBJPEG_REAL}    (cdylib)
  lib/${DEFAULT_LIBJPEG_MAJOR}, lib/${DEFAULT_LIBJPEG_DEV}    (symlinks)
  lib/${DEFAULT_LIBTJ_REAL}, lib/${DEFAULT_LIBTJ_MAJOR}, lib/${DEFAULT_LIBTJ_DEV}"
fi
cat <<EOF
Installed libjpeg-turbo-rs-capi ${CDYLIB_VERSION} into ${STAGE_ROOT}:
${LIBRARY_SUMMARY}
  lib/pkgconfig/{libjpeg,libturbojpeg}.pc
  lib/cmake/JPEG/JPEGConfig.cmake
  share/doc/libjpeg-turbo-rs-capi/LICENSE-{MIT,APACHE}
  include/{jpeglib,jerror,jmorecfg,jconfig,turbojpeg}.h
EOF
